services:
  postgres:
    image: postgres:15-alpine
    container_name: clinic_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinic_appointment_system
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  # Swagger UI for API documentation
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: clinic_swagger_ui
    restart: unless-stopped
    environment:
      SWAGGER_JSON: /app/openapi.yaml
      BASE_URL: /
    ports:
      - '8080:8080'
    volumes:
      - ./docs/apis/openapi.yaml:/app/openapi.yaml:ro

volumes:
  postgres_data:
    driver: local

