# Digital Ocean App Platform Specification
# For use with DO App Platform (PaaS)
# Deploy with: doctl apps create --spec .do/app.yaml

name: clinic-appointment-system
region: nyc

# Database
databases:
  - name: clinic-db
    engine: PG
    version: "15"
    production: true
    cluster_name: clinic-appointment-cluster
    db_name: clinic_appointment_system
    db_user: clinic_user

# Application Service
services:
  - name: api
    github:
      repo: Nhinlee/system-design-practice
      branch: main
      deploy_on_push: true
    
    # Build configuration
    dockerfile_path: projects/clinic_appointment_system/src/Dockerfile
    
    # Instance configuration
    instance_count: 2
    instance_size_slug: professional-xs  # 1 vCPU, 1 GB RAM
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 40
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        type: SECRET
        # Will be automatically set from database connection
      - key: JWT_SECRET
        type: SECRET
        # Set this in DO dashboard
      - key: JWT_EXPIRATION
        value: "1d"
      - key: ALLOWED_ORIGINS
        value: "https://yourdomain.com"
      - key: LOG_LEVEL
        value: "info"
    
    # Routing
    routes:
      - path: /
    
    # Resource allocation
    http_port: 3000
    
    # Auto-scaling (optional)
    autoscaling:
      min_instance_count: 1
      max_instance_count: 5
      metrics:
        cpu:
          percent: 80

# Static site (optional - for future frontend)
# static_sites:
#   - name: frontend
#     github:
#       repo: Nhinlee/system-design-practice
#       branch: main
#       deploy_on_push: true
#     build_command: npm run build
#     output_dir: dist
#     routes:
#       - path: /
